---
output:
  pdf_document: default
  html_document: default
---

# Blue Nile Diamond Analysis Summary

  An analysis was conducted for the Client, Blue Nile, utilizing 1214 diamonds from their stock.  This analysis focuses on the 4Cs and how they interact with each other as well as how they interact with price, and the claims posted on Blue Nile's website. The 4Cs in this analysis are represented by carat, cut, color, and clarity. The Blue Nile claims tested are that carat is the main driver for price, and the most important of the 4Cs is cut, followed by color, then clarity does not matter very much. "Importance" was gauged in two different ways: by quantity/consumer choice and price.

  Cut refers to diamond proportion, faceting, and dimensions. Blue Nile carries "Good", "Very Good", "Ideal", and "Astor Ideal" cuts. in the diamond set, there are 739 "Ideal", 382 "Very Good", 73 "Good", and 20 "Astor Ideal" cut diamonds. Color refers to how colorless a diamond is.  Blue Nile carries colors "D" through "J", which have a spread of approximately 150-200 diamonds in each category except "J", only containing approximately 100 diamonds. The colors "D-F" are considered "colorless" and "G-J" are considered "nearly colorless"; these two encompassing categories each contain about an even amount of the diamond sample. Clarity refers to "flaws" and "characteristics" of a diamond, and grading is typically based on the visibility of these flaws. The grades available are "Slightly Included (SI2-SI1)", "Very Slightly Included (VS2-VS1)", "Very, Very, Slighty Included (VVS2-VVS1)" and "Flawless (IF-FL)".  The individual components of these pairings each range from approximately 150-250 diamonds each except for the "Flawless" category, which only contains 49 "IF" and 3 "FL" diamonds. Carat refers to the weight of the diamond. Of the 1214 diamonds, 880 are below 1 carat in weight. Another 198 diamonds weigh 1 carat up to (but not including) 1.5 carats.

  To further analyze the data, diamonds were broken up into carat groupings based on Blue Nile's carat sizing chart. By comparing each of the 4Cs to each other using graphs, certain conclusions could be drawn with regard to price and quantity. Blue Nile's website claims hold true on a quantity basis.  A large majority of the stock is based on an "Ideal" cut, regardless of color, indicating the importance of quality cuts. When including clarity, distribution was relatively even across all colors.  This indicates that clarity is not a very important factor with regard to quantity overall and that color is a more important deciding factor.  Additionally, when compared to cut, the sample quality data reveals that carried diamonds often prioritized better cuts over clarity. Cut and color show a fairly consistent spread across each of their respective categories for 0.25-1.5 carat ranges (with some gapping in 0.75-1 carat range). This indicates that carat is more up to preference. The quantity characteristics of diamonds carried likely trend with the buying habits of customers.  Based on consumer/market choice, cut is the most important, followed by color, then clarity, with carat being a matter of preference.
  
  Price tells a different story when viewing the 4Cs by graph and table. When viewing the data by graph, "Very Good" cut outperforms the "Ideal" cut in price, which suggests that while it might be more important to consumers, it will not be the most important for price. Graphs of color show that "colorless" diamonds are worth more than "near colorless" diamonds, as expected, and that color will play a significant roll in price. When viewing clarity, the graphs do not show a clear trend, with most categories appearing very similar with regard to price in the zoomed in graph and inconsistent pricing between qualities for the zoomed out graph.  This would suggest that clarity is not very important to price, however table values show a clearer picture. Since carat is numerical, it can be graphed linearly with relation to price after some mathematical alterations. After these alterations, carat accounts for 89.59% of price differences, leaving only a potential 10% of the difference for the other variables.
  
  When viewing the table for maximum minus minimum average price ranges between carat and each of the three remaining Cs, then comparing the individual evaluations to each other, price rankings were achieved. Carat remains the most important, due to driving price for diamonds under 0.75 carats, which accounts for 65% of the data. Carat has the second highest price range for a majority of carat ranges, followed by color, then cut. This gives evidence to the Blue Nile claim that carat is the main driver of price, but provides evidence against the claims that the most "important" variables in order are cut, color, clarity, then carat is by preference.
  
  
  
